/**
 * Created by victorjose.gallego on 2/4/16.
 */
export const TYPES = Object.freeze({
    ADD_TASK_IN_LINK: 'ADD_TASK_IN_LINK',
    SET_SELECTED_TASK: 'SET_SELECTED_TASK',
    DELETE_TASK: 'DELETE_TASK',
    SAVE_TASK: 'SAVE_TASK',
    UNDO: 'GAME_EDITOR_UNDO',
    REDO: 'GAME_EDITOR_REDO',
    CLEAR_DIAGRAM: 'CLEAR_DIAGRAM',
    MOVE_TASK: 'MOVE_TASK',
    SAVE_EDGE: 'SAVE_EDGE',
    SET_CLEAN: 'SET_CLEAN',
    REQUEST: 'REQUEST',
    REQUEST_FAILURE: 'REQUEST_FAILURE',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    SET_SELECTED_WORKFLOW: 'SET_SELECTED_WORKFLOW',
    SELECTED_WORKFLOW_REQUEST_FAILURE: 'SELECTED_WORKFLOW_REQUEST_FAILURE',
    CLEAR_HISTORY: 'CLEAR_HISTORY'

});

export default TYPES