export const TYPES = Object.freeze({
    ADD_TASK_IN_LINK: 'ADD_TASK_IN_LINK',
    SET_SELECTED_TASK: 'SET_SELECTED_TASK',
    DELETE_TASK: 'DELETE_TASK',
    SAVE_TASK: 'SAVE_TASK',
    UNDO: 'GAME_EDITOR_UNDO',
    REDO: 'GAME_EDITOR_REDO',
    CLEAR_DIAGRAM: 'CLEAR_DIAGRAM',
    SAVE_EDGE: 'SAVE_EDGE',
    REQUEST: 'REQUEST',
    REQUEST_FAILURE: 'REQUEST_FAILURE',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    SET_SELECTED_WORKFLOW: 'SET_SELECTED_WORKFLOW',
    SELECTED_WORKFLOW_REQUEST_FAILURE: 'SELECTED_WORKFLOW_REQUEST_FAILURE',
    CLEAR_HISTORY: 'CLEAR_HISTORY',
    SET_ROLES: 'SET_ROLES',
    SET_ROLES_FAILURE: 'SET_ROLES_FAILURE',
    SET_OPERATORS: 'SET_OPERATORS',
    SET_OPERATORS_FAILURE: 'SET_OPERATORS_FAILURE',
    SET_PROPERTIES: 'SET_PROPERTIES',
    SET_PROPERTIES_FAILURE: 'SET_PROPERTIES_FAILURE',
    TOGGLE_MANAGE_TASK: 'TOGGLE_MANAGE_TASK',
    SET_MANAGE_TASK: 'SET_MANAGE_TASK',
    SET_ZOOM: 'SET_ZOOM',
    SET_MODIFIED: 'SET_MODIFIED'
});

export default TYPES