export const TYPES = {
    REQUEST : Symbol('REQUEST'),
    REQUEST_SUCCESS : Symbol('LOGIN_SUCCESS'),
    REQUEST_FAILURE : Symbol('LOGIN_FAILURE'),
    SET_ERROR: Symbol('SET_ERROR'),
    LOGGED_USER_REQUEST_SUCCESS: Symbol('LOGGED_USER_REQUEST_SUCCESS')
};

export default TYPES