export const TYPES = {
    REQUEST : Symbol('REQUEST'),
    REQUEST_SUCCESS : Symbol('REQUEST_SUCCESS'),
    REQUEST_FAILURE : Symbol('REQUEST_FAILURE'),
    ADD_REQUEST_SUCCESS : Symbol('ADD_REQUEST_SUCCESS'),
    REQUEST_TAGS_SUCCESS : Symbol('REQUEST_TAGS_SUCCESS'),
    REQUEST_TAGS_FAILURE : Symbol('REQUEST_TAGS_FAILURE'),
    REQUEST_DESIGNERS_SUCCESS : Symbol('REQUEST_DESIGNERS_SUCCESS'),
    REQUEST_DESIGNERS_FAILURE : Symbol('REQUEST_DESIGNERS_FAILURE'),
    SET_SELECTED_QUESTIONNAIRE : Symbol('SET_SELECTED_QUESTIONNAIRE'),
    SELECTED_QUESTIONNAIRE_REQUEST_FAILURE : Symbol('SELECTED_QUESTIONNAIRE_REQUEST_FAILURE'),
    SET_ERROR: Symbol('SET_ERROR'),
};

export default TYPES